backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "kitaplar"
    label: "Kitaplar"
    folder: "kitaplar"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Başlık", name: "title", widget: "string" }
      - { label: "Açıklama", name: "description", widget: "text" }
      - { label: "Kapak Görseli", name: "cover", widget: "image" }
      - { label: "Bölüm İçeriği", name: "body", widget: "markdown" }

  - name: "hakkimda"
    label: "Hakkımda"
    files:
      - file: "data/hakkimda.md"
        label: "Yazar Hakkında"
        name: "hakkimda"
        fields:
          - { label: "İçerik", name: "body", widget: "markdown" }
